#!/usr/bin/env python3
# Copyright (C) 2022 Then Try This
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Common Good Public License Beta 1.0 as
# published at http://www.cgpl.org
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Common Good Public License Beta 1.0 for more details.

# This script creates a command line interface for building and updating
# the climate tool database, as well as providing documentation of the
# recipes for how it's done

import yaml
import os,sys
from builder import climate_db
from builder import ukcri
from builder import index_multiple_deprivation as imd
from builder import link_geom_climate
from builder import network
from builder import network_from_json
from builder import stats
from builder import nfvi_sfri
from builder import hierarchy
from builder import chessscape

def load_config():
    with open('config.yml') as f:
        return yaml.load(f,Loader=yaml.FullLoader)

conf = load_config()
db = climate_db.db(conf)

# all tables should be dropped and recreated when rerunning commands

if len(sys.argv)<2 or sys.argv[1]=="-?" or sys.argv[1]=="--help":
    print("Welcome to the climate tool database builder")
else:
    if sys.argv[1]=="uk_cri":
        ukcri.load(db,conf['uk_cri_data_path'])

    if sys.argv[1]=="lsoa":
        # import lsoa from GCS_OSGB_1936 (27700)
        db.load_shp_geom(conf['lsoa_data_shp'],"lsoa","27700")
        imd.prepare_col(db,"lsoa")

    if sys.argv[1]=="msoa": 
        # import msoa from GCS_OSGB_1936 (27700)
        db.load_shp_geom(conf['msoa_data_shp'],"msoa","27700")
        imd.prepare_col(db,"msoa")

    if sys.argv[1]=="counties": 
        # import lsoa from lat/lng
        db.load_shp_geom(conf['counties_data_shp'],"counties","4326") 
        imd.prepare_col(db,"counties")

    if sys.argv[1]=="add_imd":
        imd.prepare_col(db,"lsoa")
        imd.prepare_col(db,"msoa")
        imd.prepare_col(db,"counties")
        
    if sys.argv[1]=="lsoa_imd":
        # v slow
        imd.load_lsoa(db,conf['imd_data_lsoa_csv'])

    if sys.argv[1]=="msoa_imd":
        imd.load_msoa(db,conf['imd_data_msoa_csv'])

    if sys.argv[1]=="counties_imd":
        imd.load_counties(db);

    if sys.argv[1]=="link_lsoa":
        link_geom_climate.multi(db,"lsoa")

    if sys.argv[1]=="link_msoa":
        link_geom_climate.multi(db,"msoa")

    if sys.argv[1]=="link_counties":
        link_geom_climate.multi(db,"counties")

    if sys.argv[1]=="nuke_network":
        network.reset(db)

    if sys.argv[1]=="network":
        network.load(db,conf['network_path'])

    if sys.argv[1]=="stats":
        stats.compute(db)

    if sys.argv[1]=="nfvi_sfri":         
        db.load_shp_geom(conf['nfvi_sfri_shp'],"nfvi_sfri","27700")

    if sys.argv[1]=="link_nfvi_sfri_lsoa":         
        nfvi_sfri.import_to_lsoa(db)
        
    if sys.argv[1]=="hierarchy_msoa_to_lsoa":         
        hierarchy.lsoa_to_msoa(db)
        
    if sys.argv[1]=="hierarchy_county_to_lsoa":         
        hierarchy.lsoa_to_counties(db)
        
    if sys.argv[1]=="link_nfvi_sfri_msoa":         
        nfvi_sfri.import_to_table(db,"msoa","msoa")

    if sys.argv[1]=="link_nfvi_sfri_counties":         
        nfvi_sfri.import_to_table(db,"counties","county")

    if sys.argv[1]=="chessscape_nuke":
        chessscape.nuke(db,"chessscape_seasonal")
        
    if sys.argv[1]=="chessscape_seasonal":    
        chessscape.import_seasonal_data(db,conf['chess_seasonal_path'],sys.argv[2])

    if sys.argv[1]=="chessscape_all":
        for variable in ["tas",
                         #"tasmin",
                         #"tasmax",
                         "sfcWind",
                         "pr",
                         "rlds",
                         "rsds"]:
            chessscape.import_seasonal_data(db,conf['chess_seasonal_path'],variable)

    if sys.argv[1]=="chessscape_nuke_averages":
        chessscape.nuke_averages(db,"chessscape_seasonal_averages")
        
    if sys.argv[1]=="chessscape_seasonal_averages":
        for variable in ["tas",
                         #"tasmin",
                         #"tasmax",
                         "sfcWind",
                         "pr",
                         "rlds",
                         "rsds"]:
            chessscape.import_seasonal_averages(db,conf['chess_seasonal_path'],variable)

    if sys.argv[1]=="chessscape_grid":         
        chessscape.import_grid(db)

    if sys.argv[1]=="network_json":
        network_from_json.load(db,conf['network_json'],"Heat")

    if sys.argv[1]=="network_refs":
        network_from_json.load_refs(db,conf['refs'])
        
    if sys.argv[1]=="all":
        #ukcri.load(db,conf['uk_cri_data_path'])
        #db.load_shp_geom(conf['lsoa_data_shp'],"lsoa","27700")
        #db.load_shp_geom(conf['msoa_data_shp'],"msoa","27700")
        #db.load_shp_geom(conf['counties_data_shp'],"counties","4326")
        #imd.prepare_col(db,"lsoa")
        #imd.prepare_col(db,"msoa")
        #imd.prepare_col(db,"counties")

        #link_geom_climate.simple(db,"lsoa")
        #link_geom_climate.multi(db,"msoa")
        #link_geom_climate.multi(db,"counties")

        #imd.load_msoa(db,conf['imd_data_msoa_csv'])
        #imd.load_counties(db);
        imd.load_lsoa(db,conf['imd_data_lsoa_csv'])
